### ISSUE TITLE
Needs updated with cryptography crack

### ISSUE THREAD

**Issue by MatthewFrench** [lsapan/pgoapi-swift#28] opened 2016-08-07 02:38 UTC
They cracked the unknown6 cryptography in the original pgoapi. Needs updated here.

**Comment by kilabyte** [comment] 2016-08-07 05:24
Already an issue for this. Mod please close this.

**Comment by lsapan** [comment] 2016-08-07 14:21
Duplicate of #23.

**Closed as completed by lsapan** 2016-08-07 14:21 UTC
